# PAGE OBJECTS FILE >>> (autogenerated)


class Page(object):
    html = "html"
    css_1 = 'img[src="../../../../assets/weblogo.png"]'
    css_2 = 'a[href="/login/registerImmigrantType"]'
    css_3 = 'p-radiobutton[name="type"] div:nth-of-type(2)'
    css_4 = 'button[title="Proceed"]'
    css_5 = 'p-dropdown[name="title"] span'
    css_6 = 'p-dropdown[name="title"] div:nth-of-type(3) ul p-dropdownitem:nth-of-type(2) li div'
    css_7 = 'input[placeholder="First Name"]'
    css_8 = 'input[placeholder="Last Name"]'
    css_9 = 'p-dropdown[name="visatype"] div:nth-of-type(2)'
    css_10 = 'p-dropdown[name="visatype"] div:nth-of-type(3) div input'
    css_11 = 'li:contains("India - 91")'
    css_12 = 'input[name="phone"]'
    css_13 = 'input[placeholder="Email "]'
    css_14 = 'input[placeholder="Password"]'
    css_15 = 'input[placeholder="Confirm Password"]'
    css_16 = "span.mat-checkbox-inner-container"
    css_17 = 'p-radiobutton[label="No"] div:nth-of-type(2)'
